name: CI practice

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          maven-version: '3.8.1'
          distribution: 'temurin'

      - name: Compile
        run: mvn compile
#
#      - name: Build
#        run: mvn clean verify

  build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          maven-version: '3.8.1'
          distribution: 'temurin'

#      - name: Run tests
#        run: mvn test
      - name: Build
        run: mvn clean verify

      - name: 테스트 결과 Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
        with:
          files: '**/target/surefire-reports/*.xml'  # Surefire Plugin의 테스트 결과 경로
          check_name: Maven Test Results